fixtures:
  forge_modules:
    stdlib:
      repo: 'puppetlabs-stdlib'
      ref:  '4.2.2'
    apache:
      repo: 'puppetlabs-apache'
      ref:  '1.0.1'
    concat:
      repo: 'puppetlabs-concat'
      ref:  '1.1.0'
  symlinks:
    puppet: "#{source_dir}"
